# Generated by Django 4.2.16 on 2025-02-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس'),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
