# Generated by Django 4.2.16 on 2025-02-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='linkedin')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('whatsApp', models.URLField(blank=True, null=True, verbose_name='whatsApp')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='telegram')),
                ('logo', models.FileField(null=True, upload_to='images/')),
                ('image', models.FileField(null=True, upload_to='images/')),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('context', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Us',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.AddField(
            model_name='faq',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
